### ISSUE TITLE
Multioutput example is not truly multioutput?

### ISSUE THREAD

**Issue by cottrell** [Molecolab-Pisa/GPX#2]
If you look at the example

https://github.com/Molecolab-Pisa/GPX/blob/main/examples/multioutput.ipynb

I think the covariance and the kernel has the wrong shape for typical multioutput? i.e. it should be something like m x m x d x d or some reshaped version of that?

I'm not sure yet if the kernel active_dims can be used to acheive full multi-output or if there is some other approach. I just quickly was looking at the multoutput example.

**Comment by ecignoni** [comment]
Hi @cottrell 

I agree that the example could be documented better. The way multiple outputs are handled as for now is to use a single kernel (that is, the hyperparameters are the same for all the outputs), and only the coefficients are fitted for each output. It is not a full multiple-output GP in the traditional sense. It's more like how multiple outputs are handled for kernel methods in scikit-learn, if I'm not mistaken.

**Comment by cottrell** [comment]
> Hi @cottrell
> 
> I agree that the example could be documented better. The way multiple outputs are handled as for now is to use a single kernel (that is, the hyperparameters are the same for all the outputs), and only the coefficients are fitted for each output. It is not a full multiple-output GP in the traditional sense. It's more like how multiple outputs are handled for kernel methods in scikit-learn, if I'm not mistaken.

Ok that's fine was just wondering if it was missing some feature accidentally.
